name: rajiv
favicon: null
layout_spectrum: 0.8527
typography_spectrum: 0.9931
title: Rajiv Ayyangar
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8a431'
    - '#ffffff'
    - '#000000'
    - '#f9c79b'
    - '#624112'
  brandStrength: 0.8571245707571507
  lightness: 0.7032517387997359
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
